CREATE TABLE "NameMaps" (
    "NameMapId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_NameMaps" PRIMARY KEY ("NameMapId")
);


CREATE TABLE "Blogs" (
    "BlogId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NULL,
    "NameMapId" integer NOT NULL,
    CONSTRAINT "PK_Blogs" PRIMARY KEY ("BlogId"),
    CONSTRAINT "FK_Blogs_NameMaps_NameMapId" FOREIGN KEY ("NameMapId") REFERENCES "NameMaps" ("NameMapId") ON DELETE RESTRICT
);
COMMENT ON TABLE "Blogs" IS 'Blogs by Edward';


CREATE TABLE "Posts" (
    "PostId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" varchar(200) NULL,
    "Content" character varying(500) NOT NULL,
    "Pay" numeric(14,2) NOT NULL,
    "LastUpated" timestamp without time zone NOT NULL,
    "MainBlogId" integer NOT NULL,
    "SubBlogId" integer NOT NULL,
    "NameMapId" integer NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("PostId"),
    CONSTRAINT "FK_Posts_Blogs_MainBlogId" FOREIGN KEY ("MainBlogId") REFERENCES "Blogs" ("BlogId") ON DELETE CASCADE,
    CONSTRAINT "FK_Posts_Blogs_SubBlogId" FOREIGN KEY ("SubBlogId") REFERENCES "Blogs" ("BlogId") ON DELETE CASCADE,
    CONSTRAINT "FK_Posts_NameMaps_NameMapId" FOREIGN KEY ("NameMapId") REFERENCES "NameMaps" ("NameMapId") ON DELETE CASCADE
);
COMMENT ON TABLE "Posts" IS 'Posts by Edward';
COMMENT ON COLUMN "Posts"."Title" IS 'The Title of the Post';


CREATE UNIQUE INDEX "IX_Blogs_NameMapId" ON "Blogs" ("NameMapId");


CREATE INDEX "IX_Posts_MainBlogId" ON "Posts" ("MainBlogId");


CREATE UNIQUE INDEX "IX_Posts_NameMapId" ON "Posts" ("NameMapId");


CREATE INDEX "IX_Posts_SubBlogId" ON "Posts" ("SubBlogId");



