CREATE TABLE "Books" (
    "BookId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NULL,
    "_privateKey" text NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("BookId")
);


CREATE TABLE "Cars" (
    "LicensePlate" text NOT NULL,
    "State" text NOT NULL,
    "DisplayName" text GENERATED ALWAYS AS ("State" || ', ' ||  "LicensePlate") STORED,
    "Make" character varying(50) NOT NULL,
    "Model" character varying(10) NOT NULL,
    CONSTRAINT "PK_Cars" PRIMARY KEY ("State", "LicensePlate")
);


CREATE TABLE "NameMaps" (
    "NameMapId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_NameMaps" PRIMARY KEY ("NameMapId")
);


CREATE TABLE "Tags" (
    "TagId" text NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("TagId")
);


CREATE TABLE "Blogs" (
    "BlogId" integer NOT NULL,
    "Url" text NULL,
    "NameMapId" integer NOT NULL,
    CONSTRAINT "PK_Blogs" PRIMARY KEY ("BlogId"),
    CONSTRAINT "FK_Blogs_NameMaps_NameMapId" FOREIGN KEY ("NameMapId") REFERENCES "NameMaps" ("NameMapId") ON DELETE RESTRICT
);
COMMENT ON TABLE "Blogs" IS 'Blogs by Edward';


CREATE TABLE "Posts" (
    "PostId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Title" varchar(200) NULL,
    "Content" character varying(500) NOT NULL,
    "Pay" numeric(14,2) NOT NULL,
    "LastUpated" timestamp without time zone NOT NULL,
    "MainBlogId" integer NOT NULL,
    "SubBlogId" integer NOT NULL,
    "NameMapId" integer NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("PostId"),
    CONSTRAINT "FK_Posts_Blogs_MainBlogId" FOREIGN KEY ("MainBlogId") REFERENCES "Blogs" ("BlogId") ON DELETE CASCADE,
    CONSTRAINT "FK_Posts_Blogs_SubBlogId" FOREIGN KEY ("SubBlogId") REFERENCES "Blogs" ("BlogId") ON DELETE CASCADE,
    CONSTRAINT "FK_Posts_NameMaps_NameMapId" FOREIGN KEY ("NameMapId") REFERENCES "NameMaps" ("NameMapId") ON DELETE CASCADE
);
COMMENT ON TABLE "Posts" IS 'Posts by Edward';
COMMENT ON COLUMN "Posts"."Title" IS 'The Title of the Post';


CREATE TABLE "PostTags" (
    "PostId" integer NOT NULL,
    "TagId" text NOT NULL,
    "PublicationDate" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_PostTags" PRIMARY KEY ("PostId", "TagId"),
    CONSTRAINT "FK_PostTags_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("PostId") ON DELETE CASCADE,
    CONSTRAINT "FK_PostTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("TagId") ON DELETE CASCADE
);


CREATE UNIQUE INDEX "IX_Blogs_NameMapId" ON "Blogs" ("NameMapId");


CREATE INDEX "IX_Posts_MainBlogId" ON "Posts" ("MainBlogId");


CREATE UNIQUE INDEX "IX_Posts_NameMapId" ON "Posts" ("NameMapId");


CREATE INDEX "IX_Posts_SubBlogId" ON "Posts" ("SubBlogId");


CREATE INDEX "IX_PostTags_TagId" ON "PostTags" ("TagId");



